/**
 * Expo Config Plugin for Splash Screen Copyright Text
 *
 * This plugin adds dynamic copyright text to the splash screen:
 * - iOS: Uses post-prebuild script (scripts/add-ios-splash-copyright.js)
 * - Android: Creates a custom splash screen layout with copyright text
 *
 * Note: iOS splash screen modification is done as a post-prebuild step because
 * expo-splash-screen's base mod overwrites any changes made during the plugin chain.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const COPYRIGHT_TEXT = `©${new Date().getFullYear()} Thrive Community Church\nAll Rights Reserved`;

/**
 * Add copyright label to iOS SplashScreen.storyboard
 *
 * Note: This is intentionally a no-op during prebuild.
 * The iOS storyboard is modified by scripts/add-ios-splash-copyright.js
 * which runs AFTER prebuild completes (after expo-splash-screen's base mod writes the file).
 */
const withIosSplashCopyright = (config) => {
  // iOS splash screen copyright is handled by post-prebuild script
  // because expo-splash-screen's base mod overwrites any changes made during the plugin chain
  console.log('ℹ️  iOS splash copyright will be added by post-prebuild script');
  return config;
};

/**
 * Add copyright text to Android splash screen
 * This creates a custom layout with copyright text overlay matching iOS constraints
 */
const withAndroidSplashCopyright = (config) => {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const androidResPath = path.join(projectRoot, 'android', 'app', 'src', 'main', 'res');

      if (!fs.existsSync(androidResPath)) {
        console.warn('⚠️  Android res directory not found');
        return config;
      }

      // Create values directory if it doesn't exist
      const valuesDir = path.join(androidResPath, 'values');
      if (!fs.existsSync(valuesDir)) {
        fs.mkdirSync(valuesDir, { recursive: true });
      }

      // Create or update strings.xml with copyright text
      const stringsPath = path.join(valuesDir, 'strings.xml');
      let stringsContent = '';

      if (fs.existsSync(stringsPath)) {
        stringsContent = fs.readFileSync(stringsPath, 'utf8');

        // Update existing copyright string if it exists
        if (stringsContent.includes('splash_copyright')) {
          // Replace the existing copyright string with the correct one
          stringsContent = stringsContent.replace(
            /<string name="splash_copyright">.*?<\/string>/,
            `<string name="splash_copyright">${COPYRIGHT_TEXT.replace(/\n/g, '\\n')}</string>`
          );
          fs.writeFileSync(stringsPath, stringsContent, 'utf8');
          console.log('✅ Updated Android copyright string');
        } else {
          // Add new copyright string
          const copyrightString = `  <string name="splash_copyright">${COPYRIGHT_TEXT.replace(/\n/g, '\\n')}</string>`;
          stringsContent = stringsContent.replace('</resources>', `${copyrightString}\n</resources>`);
          fs.writeFileSync(stringsPath, stringsContent, 'utf8');
          console.log('✅ Added Android copyright string');
        }
      } else {
        stringsContent = `<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="splash_copyright">${COPYRIGHT_TEXT.replace(/\n/g, '\\n')}</string>
</resources>`;
        fs.writeFileSync(stringsPath, stringsContent, 'utf8');
        console.log('✅ Created Android strings.xml with copyright');
      }

      // Create layout directory if it doesn't exist
      const layoutDir = path.join(androidResPath, 'layout');
      if (!fs.existsSync(layoutDir)) {
        fs.mkdirSync(layoutDir, { recursive: true });
      }

      // Create custom splash screen layout with copyright text
      // Matches iOS constraints: edge-to-edge with 20dp bottom padding
      const splashLayoutPath = path.join(layoutDir, 'splash_screen.xml');
      const splashLayout = `<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/splashscreen_background">

    <!-- Background Image (generated by expo-splash-screen) -->
    <ImageView
        android:id="@+id/splashscreen_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:src="@drawable/splashscreen_logo"
        android:scaleType="centerCrop"
        android:contentDescription="@null" />

    <!-- Copyright Text - matches iOS constraints (edge-to-edge, 20dp bottom) -->
    <TextView
        android:id="@+id/copyright_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:layout_marginBottom="20dp"
        android:paddingTop="8dp"
        android:paddingBottom="8dp"
        android:text="@string/splash_copyright"
        android:textColor="@android:color/white"
        android:textSize="14sp"
        android:textAlignment="center"
        android:gravity="center"
        android:lineSpacingMultiplier="1.2" />
</FrameLayout>
`;

      fs.writeFileSync(splashLayoutPath, splashLayout, 'utf8');
      console.log('✅ Created Android splash screen layout with copyright text (matches iOS)');

      return config;
    },
  ]);
};

/**
 * Main plugin function
 */
const withSplashScreenCopyright = (config) => {
  config = withIosSplashCopyright(config);
  config = withAndroidSplashCopyright(config);
  return config;
};

module.exports = withSplashScreenCopyright;

